// Generated by CoffeeScript 1.3.3
(function() {
  var btn, calc, controller1, db, rows, win,
    _this = this;

  win = Ti.UI.createWindow({
    title: 'Home'
  });

  btn = Ti.UI.createButton({
    title: 'nextWindow'
  });

  win.add(btn);

  win.open();

  btn.addEventListener('click', function() {
    var nextWin;
    nextWin = Ti.UI.createWindow({
      title: 'Next'
    });
    return nextWin.open();
  });

  controller1 = new HomeViewController;

  controller1.open();

  controller1.view.on('click:button', function() {
    var controller2;
    controller2 = new NextViewController;
    return controller1.presentViewController(controller2);
  });

  Ti.App.addEventListener('calculated', function(params) {
    return alert("計算終了! " + params.total);
  });

  btn = Ti.UI.createButton({
    title: '計算'
  });

  btn.addEventListener('click', function() {
    return Ti.App.fireEvent('calculated', {
      total: xxx
    });
  });

  calc = new Calclator;

  calc.on('calculated', function() {
    return alert("計算終了! " + this.total);
  });

  btn = Ti.UI.createButton({
    title: '計算'
  });

  btn.addEventListener('click', function() {
    return calc.calculate(10, 20);
  });

  db = Ti.Database.open('mydb');

  rows = db.execute('SELECT * FROM hoge WHERE id = ?', id);

  db.execute('INSERT INTO hoge (txt) values (?)', 'foobar');

  db.close();

}).call(this);
